name: Build and Deploy My Container

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches: [master]
  #   types: [opened, synchronize]

jobs:
  build_publish_gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deployment
        uses: convictional/gcp-github-action@v1.0.1
        with:
          application_credentials: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          commands: "gcloud builds submit --tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/wp-gcloud-run|gcloud run deploy wordpress --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/wp-gcloud-run --platform managed --region europe-north1 --set-env-vars ${{ secrets.WP_ENVS }} --project=${{ secrets.GCLOUD_PROJECT_ID }} --port 80"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
    