name: Build and Deploy My Container

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches: [master]
  #   types: [opened, synchronize]

jobs:
  build_publish_gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Authenticate with google cloud

        uses: actions/gcloud/auth@master
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Push to Goolge Cloud Registry
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud builds submit --tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/wp-gcloud-run"

      - name: Deploy to cloud run
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud beta run deploy wordpress --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/wp-gcloud-run --platform managed  --region europe-north1 --set-env-vars ${{ secrets.WP_ENVS }} --project=${{ secrets.GCLOUD_PROJECT_ID }} --port 80"
      
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
    