name: Build and Deploy My Container

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build_publish_gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Authenticate with google cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Push to Goolge Cloud Registry
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && 
            gcloud auth configure-docker && docker build -t ${{ secrets.GCLOUD_PROJECT_ID }} . &&
            docker tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/wp-gcloud-run && 
            docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/wp-gcloud-run"

